# Generated by Django 5.0.6 on 2024-06-06 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionpath',
            options={'verbose_name': 'Путь производства', 'verbose_name_plural': 'Путь производства'},
        ),
    ]
