# Generated by Django 5.0.6 on 2024-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_productionpath_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='image',
            field=models.FileField(upload_to='production_images', verbose_name='Картинка производства'),
        ),
        migrations.AlterField(
            model_name='productionpath',
            name='image_1',
            field=models.FileField(upload_to='production_path_images', verbose_name='Картинка_1'),
        ),
        migrations.AlterField(
            model_name='productionpath',
            name='image_2',
            field=models.FileField(upload_to='production_path_images', verbose_name='Картинка_2'),
        ),
        migrations.AlterField(
            model_name='productionpath',
            name='image_3',
            field=models.FileField(upload_to='production_path_images', verbose_name='Картинка_3'),
        ),
        migrations.AlterField(
            model_name='productionpath',
            name='image_4',
            field=models.FileField(upload_to='production_path_images', verbose_name='Картинка_4'),
        ),
        migrations.AlterField(
            model_name='productionpath',
            name='image_5',
            field=models.FileField(upload_to='production_path_images', verbose_name='Картинка_5'),
        ),
        migrations.AlterField(
            model_name='productionpath',
            name='image_6',
            field=models.FileField(upload_to='production_path_images', verbose_name='Картинка_6'),
        ),
        migrations.AlterField(
            model_name='productionshort',
            name='image',
            field=models.FileField(upload_to='production_short_images', verbose_name='Картинка производства'),
        ),
    ]
