# Generated by Django 5.0.6 on 2024-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_specific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.FileField(upload_to='news_images', verbose_name='Фотография'),
        ),
    ]
