# Generated by Django 5.0.6 on 2024-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='specific',
            field=models.CharField(max_length=5000, null=True, verbose_name='Определите вакансию, для разных языков'),
        ),
    ]
