# Generated by Django 5.0.6 on 2024-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logocompany',
            name='image',
            field=models.FileField(upload_to='logo_company_images', verbose_name='Фотография логотипа компании'),
        ),
    ]
