# Generated by Django 5.0.6 on 2024-06-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandinfo',
            name='title_1',
            field=models.CharField(max_length=5000, null=True, verbose_name='1 загланая'),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='title_2',
            field=models.CharField(max_length=5000, null=True, verbose_name='2 загланая'),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='title_3',
            field=models.CharField(max_length=5000, null=True, verbose_name='3 загланая'),
        ),
        migrations.AddField(
            model_name='brandinfo',
            name='title_4',
            field=models.CharField(max_length=5000, null=True, verbose_name='4 загланая'),
        ),
    ]
