# Generated by Django 5.0.6 on 2024-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_info', '0002_brandinfo_title_1_brandinfo_title_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandhistory',
            name='image',
            field=models.FileField(upload_to='logo_images', verbose_name='Логотип для истории бренда'),
        ),
    ]
