# Generated by Django 5.0.6 on 2024-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flavor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavor',
            name='image',
            field=models.FileField(upload_to='flavor_images', verbose_name='Фотография вкуса'),
        ),
    ]
