# Generated by Django 5.0.6 on 2024-06-17 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image_logo',
            field=models.FileField(blank=True, null=True, upload_to='brand_logo_images', verbose_name='Фотография логотипа бренда'),
        ),
    ]
