# Generated by Django 5.0.6 on 2024-06-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_image_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='background_images', verbose_name='Фотография фона'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_circle',
            field=models.FileField(blank=True, null=True, upload_to='brand_circle_images', verbose_name='Фотография бренда'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image_main',
            field=models.FileField(blank=True, null=True, upload_to='brand_main_images', verbose_name='Главная фотография бренда'),
        ),
    ]
